#name: 🎭 Playwright Tests
#on:
#    pull_request:
#        branches: [ "develop" ]
#jobs:
#    test:
#        timeout-minutes: 60
#        runs-on: ubuntu-latest
#        steps:
#            -   uses: actions/checkout@v3
#            -   uses: actions/setup-node@v3
#                with:
#                    node-version: 18
#            -   name: Install dependencies and build
#                run: |
#                    npm i
#                    npm ci
#                    npm run build
#            - name: Start WordPress Environment
#              run: |
#                  npm run env:start
#            -   name: Install Playwright Browsers
#                run: npx playwright install chromium
#            -   name: Run Playwright tests
#                run: npm run test:playwright
#            -   uses: actions/upload-artifact@v3
#                if: always()
#                with:
#                    name: playwright-report
#                    path: playwright-report/
#                    retention-days: 30
